@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mod.rozbrajaczpoziomow.testing.effects;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;