@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mod.rozbrajaczpoziomow.testing.datagen.struct;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;