@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mod.rozbrajaczpoziomow.testing.a_registers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;