@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mod.rozbrajaczpoziomow.testing.entities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;